# Generated by Django 5.0.14 on 2025-08-26 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre1", models.CharField(max_length=64)),
                ("nombre2", models.CharField(max_length=64, null=True)),
                ("apellido1", models.CharField(max_length=64)),
                ("apellido2", models.CharField(max_length=64, null=True)),
                (
                    "nombreCompleto",
                    models.CharField(
                        default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                        max_length=124,
                    ),
                ),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("fechaRegistro", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=64)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SA", "Administrador"),
                            ("CLIENTE", "Cliente"),
                            ("TIENDA", "Tienda"),
                        ],
                        default="CLIENTE",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=16, unique=True)),
                ("nombreComercial", models.CharField(max_length=124)),
                ("descripcion", models.TextField()),
                (
                    "administrador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin",
                        to="tienda.usuario",
                    ),
                ),
            ],
        ),
    ]
