# Generated by Django 5.0.14 on 2025-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credencial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ultimoAcceso", models.DateField(auto_now_add=True)),
                ("fechaCreacion", models.DateField(auto_now_add=True)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="password",
        ),
        migrations.AddField(
            model_name="usuario",
            name="credenciales",
            field=models.ManyToManyField(
                blank=True, related_name="credenciales", to="tienda.credencial"
            ),
        ),
    ]
